# frontend/Dockerfile

# 1단계: 빌드
FROM node:18 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# 2단계: 정적 파일 서빙
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

# nginx 기본 설정 사용
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
